---
title: "RWorksheet_urdas#3b"
author: "Cindy Urdas"
date: "2022-11-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***1.	Create a data frame using the table below.***\
 **a. Write the codes.**\
dframe <- data.frame(\
  Respondents = 1:20,\
  Sex = c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2),\
  Fathers_Occupation = c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1),\
  Persons_atHome = c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6),\
  Siblings_atSchool = c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2),\
  Types_houses = c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2))\
dframe\

**b.	Describe the data. Get the structure or the summary of the data**\
> summary(dframe)\
  Respondents         Sex       Fathers_Occupation   Persons_atHome Siblings_atSchool\
Min.   : 1.00   Min.   :1.00    Min.   :1.00        Min.   : 3.0    Min.   :1.00\   
1st Qu.: 5.75   1st Qu.:2.00    1st Qu.:1.00        1st Qu.: 5.0    1st Qu.:2.00\   
Median :10.50   Median :2.00    Median :2.00        Median : 7.0    Median :2.50\   
Mean   :10.50   Mean   :1.85    Mean   :1.95        Mean   : 6.4\   Mean   :2.95  
3rd Qu.:15.25   3rd Qu.:2.00    3rd Qu.:3.00        3rd Qu.: 8.0    3rd Qu.:4.25\   
Max.   :20.00   Max.   :2.00    Max.   :3.00        Max.   :11.0    Max.   :6.00 \  
  
  Types_houses\
   Min.   :1.0\
   1st Qu.:2.0\
   Median :2.5\
   Mean   :2.3\
   3rd Qu.:3.0\
   Max.   :3.0\ 

**c.	Is the mean number of siblings attending is 5?**\
> mean(dframe$Siblings_atSchool)\
**[1] 2.95**\	
 	***NO.***\
 	
**d.	Extract the 1st two rows and then all the columns using the subsetting functions. Write the codes and its output.**\
> extract_d <- subset(dframe[c(1:2), ])\
> extract_d\
Respondents Sex Fathers_Occupation Persons_atHome Siblings_atSchool Types_houses\
1                  1     2                                  1                           5                          6                      1\
2                  2     2                                  3                           7                          4                      2\

**e.	Extract 3rd and 5th row with 2nd and 4th column. Write the codes and its result.**\
> extract_e<- subset(dframe[c(3,5), c(2,4)])\
> extract_e\
  Sex Persons_atHome\
3    1                      3\
5    2                      5\

**f.	Select the variable types of houses then store the vector that results as types_houses. Write the codes.**\
> extract_f <- subset(dframe, select = Types_houses)\
> extract_f\

**g.	Select only all Males respondent that their father occupation was farmer. Write the codes and its output.**\
> extract_g <- subset(dframe, Sex == 1 &Fathers_Occupation < 1,select = c(Sex, Fathers_Occupation),drop = FALSE)\
> extract_g\
[1] Sex                Fathers_Occupation\
      <0 rows> (or 0-length row.names)\

**h.	Select only all females respondent that have greater than or equal to 5 number of siblings attending school. Write the codes and its outputs.**\
> extract_h <- subset(dframe,Sex == 2 & Siblings_atSchool >= 5, select = c(Sex, Siblings_atSchool), drop = FALSE)\
> extract_h\
   Sex Siblings_atSchool\
1    2               6\
7    2               5\
13   2               5\
14   2               5\
18   2               5\

**2.	Write a R program to create an empty data frame. Using the following codes:**\
df = data.frame(Ints=integer(),\
Doubles=double(), Characters=character(), Logicals=logical(),\
Factors=factor(), stringsAsFactors=FALSE)\
print("Structure of the empty dataframe:") print(str(df))\
**a.	Describe the results.**\
> df = data.frame(Ints=integer(),\
+                 
+                 Doubles=double(), Characters=character(),\
+                 Logicals=logical(),\
+                 Factors=factor(),\
+                 stringsAsFactors=FALSE)\
> 
> print("Structure of the empty dataframe:")\
**[1] "Structure of the empty dataframe:"**\
> print(str(df))\
'data.frame':	0 obs. of  5 variables:\
 $ Ints      : int\
 $ Doubles   : num\
 $ Characters: chr\
 $ Logicals  : logi\
 $ Factors   : Factor w/ 0 levels:\
NULL\

**3.	Interpret the graph.**\

***Figure 1: Sentiments of Tweets per day - Donald Trump***\

The sentiment of tweets about Donald Trump per day is shown by a graph, and tweets with negative emotions have the highest sentiment. Additionally, July 15, 2020, and July 21, 2020, which each received almost 4000 bad tweets, are the two days with the highest number of negative tweets.

 







